configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero
      config:
        region: garage
        s3ForcePathStyle: true
        s3Url: http://10.10.10.50:3900
  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: minio

credentials:
  useSecret: true
  existingSecret: velero-creds

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.10.0
    volumeMounts:
      - mountPath: /target
        name: plugins

# Disable Restic/Kopia by default for now (focus on YAMLs first)
deployNodeAgent: false

schedules:
  daily-backup:
    disabled: false
    schedule: "0 3 * * *"
    template:
      ttl: "720h" # 30 days

# Disable CRD upgrade job since we applied CRDs manually
upgradeCRDs: false
