---
# Global variables for all hosts in the inventory

# Network Configuration
network:
  gateway: 192.168.1.1
  subnet: 192.168.1.0/24
  dns_server: 192.168.1.1
  local_domain: local
  external_domain: pindaroli.org

# User Information
admin:
  email: o.pindaro@gmail.com
  name: Olindo

# Common packages
common_packages:
  - vim
  - htop
  - curl
  - wget
  - git
  - net-tools

# Timezone
timezone: Europe/Rome

# NTP servers
ntp_servers:
  - 0.it.pool.ntp.org
  - 1.it.pool.ntp.org
  - 2.it.pool.ntp.org
