apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: L2Advertisement
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"metallb.io/v1beta1","kind":"L2Advertisement","metadata":{"annotations":{},"name":"l2-advertisement","namespace":"metallb-system"},"spec":{"ipAddressPools":["my-ip-pool"]}}
    creationTimestamp: "2026-01-05T16:03:11Z"
    generation: 2
    name: l2-advertisement
    namespace: metallb-system
    resourceVersion: "358870"
    uid: 03aca054-acff-49d6-8cf3-e6e2e3194e0f
  spec:
    interfaces:
    - eth0
    ipAddressPools:
    - my-ip-pool
kind: List
metadata:
  resourceVersion: ""
