apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-nfs-stripe-arr-conf
  resources:
    requests:
      storage: 5Gi