apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-config-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    server: 10.10.10.50
    path: /mnt/stripe/k8s-n8n

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-config-pvc
  namespace: n8n
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
  volumeName: n8n-config-pv
