apiVersion: v1
kind: Service
metadata:
  name: postgres-main-metrics
  namespace: cnpg-system
  labels:
    app.kubernetes.io/name: postgres-main
    monitoring: "true"
spec:
  type: ClusterIP
  selector:
    cnpg.io/cluster: postgres-main
  ports:
    - name: metrics
      port: 9187
      targetPort: 9187
      protocol: TCP
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: postgres-main
  namespace: monitoring
  labels:
    release: victoria-monitoring
spec:
  jobLabel: postgres
  namespaceSelector:
    matchNames:
      - cnpg-system
  selector:
    matchLabels:
      monitoring: "true"
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
