apiVersion: v1
kind: Service
metadata:
  name: traefik-metrics
  namespace: traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik
    monitoring: "true"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
      protocol: TCP
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: traefik
  namespace: monitoring
  labels:
    release: victoria-monitoring
spec:
  jobLabel: traefik
  namespaceSelector:
    matchNames:
      - traefik
  selector:
    matchLabels:
      monitoring: "true"
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
