apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: velero
  namespace: monitoring
  labels:
    release: victoria-monitoring
spec:
  jobLabel: velero
  namespaceSelector:
    matchNames:
      - velero
  selector:
    matchLabels:
      app.kubernetes.io/name: velero
  endpoints:
    - port: http-monitoring
      path: /metrics
      interval: 1m
