apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin-external
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`jellyfin.pindaroli.org`)
    kind: Rule
    services:
    - name: servarr-jellyfin
      port: 8096
    middlewares:
    - name: oauth2-auth
  tls:
    secretName: pindaroli-wildcard-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lidarr-ingress-route
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`lidarr.pindaroli.org`) 
      kind: Rule
      services:
        - name: servarr-lidarr
          port: 8686
      middlewares:
        - name: oauth2-auth
      tls:
    secretName: pindaroli-wildcard-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr-ingress-route
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prowlarr.pindaroli.org`) 
      kind: Rule
      services:
        - name: servarr-prowlarr
          port: 9696
      middlewares:
        - name: oauth2-auth
      tls:
    secretName: pindaroli-wildcard-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent-ingress-route
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`qbittorrent.pindaroli.org`) 
    kind: Rule
    services:
    - name: servarr-qbittorrent-web
      port: 8080
    middlewares:
    - name: oauth2-auth
  tls:
    secretName: pindaroli-wildcard-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: replace-path
  namespace: arr
spec:
  replacePath:
    path: /
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: readarr-ingress-route
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`readarr.pindaroli.org`) 
      kind: Rule
      services:
        - name: servarr-readarr
          port: 8787
      middlewares:
        - name: oauth2-auth
      tls:
    secretName: pindaroli-wildcard-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr-ingress-route
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarr.pindaroli.org`) 
      kind: Rule
      services:
        - name: servarr-sonarr
          port: 8989
      middlewares:
        - name: oauth2-auth
      tls:
    secretName: pindaroli-wildcard-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr-ingress-route
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr.pindaroli.org`) 
      kind: Rule
      services:
        - name: servarr-radarr
          port: 7878
      middlewares:
        - name: oauth2-auth
      tls:
    secretName: pindaroli-wildcard-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr-ingress-route
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bazarr.pindaroli.org`) 
      kind: Rule
      services:
        - name: servarr-bazarr
          port: 6767
      middlewares:
        - name: oauth2-auth
      tls:
    secretName: pindaroli-wildcard-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyseerr-ingress-route
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyseerr.pindaroli.org`) 
      kind: Rule
      services:
        - name: servarr-jellyseerr
          port: 5055
      middlewares:
        - name: oauth2-auth
      tls:
    secretName: pindaroli-wildcard-tls
---
apiVersion: v1
kind: Service
metadata:
  name: dns-upstream
  namespace: default
spec:
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: dns-upstream
  namespace: default
subsets:
- addresses:
  - ip: 192.168.1.1
  ports:
  - port: 53
    protocol: TCP
    name: dns-tcp
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: dot-to-dns-proxy
  namespace: default
spec:
  entryPoints:
    - dot
  routes:
  - match: HostSNI(`*`)
    services:
    - name: dns-upstream
      port: 53
  tls:
    passthrough: true
