apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent-ingress-route
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`qbittorrent.local`) || Host(`qbittorrent.pindaroli.org`)
    kind: Rule
    services:
    - name: servarr-qbittorrent-web
      port: 8080
  tls:
    { }