apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr-ingress-route
  namespace: arr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr.local`) 
      kind: Rule
      services:
        - name: servarr-radarr
          port: 7878