# High Availability Configuration
deployment:
  replicas: 2

# Pod Anti-Affinity for Node Distribution
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - traefik
        topologyKey: kubernetes.io/hostname

# Configure Network Ports and EntryPoints
# EntryPoints are the network listeners for incoming traffic.
ports:
  # Defines the HTTP entry point named 'web'
  web:
    port: 9080
    exposedPort: 80
    nodePort: 30000
    # Instructs this entry point to redirect all traffic to the 'websecure' entry point
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true

  # Defines the HTTPS entry point named 'websecure'
  websecure:
    port: 9443
    exposedPort: 443
    nodePort: 30001

# Enables the dashboard in Secure Mode
api:
  dashboard: true
  insecure: false

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik-dash.pindaroli.org`)
    entryPoints:
      - websecure
    middlewares:
      - name: dashboard-auth
        namespace: traefik

# Creates a BasicAuth Middleware and Secret for the Dashboard Security
# and all other middlewares used across the cluster
extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: dashboard-auth-secret
    type: kubernetes.io/basic-auth
    stringData:
      username: olindo  
      password: "${TRAEFIK_DASHBOARD_PASSWORD}"      # Set via setEnv.sh
  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: dashboard-auth
    spec:
      basicAuth:
        secret: dashboard-auth-secret
  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: replace-path
    spec:
      replacePath:
        path: /
  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: oauth2-auth
    spec:
      forwardAuth:
        address: http://oauth2-proxy.oauth2-proxy.svc.cluster.local:4180/
        authResponseHeaders:
        - X-Auth-User
        - X-Auth-Email
        - X-Auth-Name
        - X-Auth-Uid
        trustForwardHeader: true
  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: oauth2-errors
    spec:
      errors:
        query: /oauth2/start?rd={url}
        service:
          name: oauth2-proxy
          namespace: oauth2-proxy
          port: 4180
        status:
        - 401-403
  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: redirect-to-https
    spec:
      redirectScheme:
        permanent: true
        scheme: https

# We will route with Gateway API instead.
ingressClass:
  enabled: false

# Enable both Gateway API Provider and KubernetesIngress provider
# Providers tell Traefik where to find routing configuration.
providers:
  kubernetesIngress:
     enabled: true
     allowEmptyServices: true
  kubernetesGateway:
     enabled: true
  kubernetesCRD:
     enabled: true
     allowCrossNamespace: true

## Gateway Listeners
gateway:
  listeners:
    web:           # HTTP listener that matches entryPoint `web`
      port: 9080
      protocol: HTTP
      namespacePolicy:
        from: All

    websecure:         # HTTPS listener that matches entryPoint `websecure`
      port: 9443
      protocol: HTTPS  # TLS terminates inside Traefik
      namespacePolicy:
        from: All
      mode: Terminate
      certificateRefs:    
        - kind: Secret
          name: pindaroli-wildcard-tls  # Certificato Let's Encrypt wildcard
          group: ""
          namespace: traefik

# Security Context to allow binding to privileged ports
securityContext:
  capabilities:
    add:
      - NET_BIND_SERVICE
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

# Enable Observability
logs:
  general:
    level: INFO
  # This enables access logs, outputting them to Traefik's standard output by default. The [Access Logs Documentation](https://doc.traefik.io/traefik/observability/access-logs/) covers formatting, filtering, and output options.
  access:
    enabled: true

# Enables Prometheus for Metrics
metrics:
  prometheus:
    enabled: true