opnsense_api_key: "ZSX93l0E7KGhroufezmO/lUnLOJYvp0y/EsDENf3lEQiDO+7T17eeCmmFiPm/6wqLQU295oUP7FccUvR"
opnsense_api_secret: "TH6OftQos0qGccrtgMq84JYi/bAlPRHfHf/4hsXR/EChI1AbHMMV/xUDxd0JYHMjfo3qK+HMzdGbLiu4"
