username: admin
password: ENC[AES256_GCM,data:+bI/BwGeif8=,iv:uqDP9/jddxNTRY/OwKn4ZlyoDt9sWbqpxheOWsot+hY=,tag:cgsdr0hCErFwbJMT5c+wQw==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVmkweHVaVEdOMlEvNE13
            NVRPQlltMFY0a25hNlhwTHdYT25sb0tackZjClRTY2VORlFPRXF5WloxTHNtNXE0
            QXAra0NXc2twUENLeGs3QkxLWC9SL2MKLS0tIEkzc01rRFEycm1JcVJsQUhFRytt
            TlRiU3R2L3lHQXNpVWMvTjFqeFVEUHMKtcchg5bFswGXqCSHgf0hPhHgT4qQb2sR
            aiD9XVNTd6OcMqfsH1sHbswbGwoZnS5selIQaUAuvYncy0N5QCptPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T19:11:46Z"
    mac: ENC[AES256_GCM,data:vn7M9BK7m7tiCDV026aPwTuXB2Z9z3AtbTbFFoh5FqUrKVbVzTIaZFHC02nF+Uhq7AigOFi3or0XWRGJjSr5pXeksyoZe/HN3uDJgUpz4tSw2GbY371PCvZDJv5sjU+G3B8j4JX1kxvs0mrT5f6zBMVbyGLFHVrbu2oBo0229DI=,iv:MJbQUAkp0LVZzY563vToLO9900ux+6pOqh+6R6//JRg=,tag:lYE4lJ26okJPww9lSF2xHw==,type:str]
    encrypted_regex: ^(deepseek_api_key|deepsearch_api_key|.*api_key|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
