ansible_ssh_pass: REDACTED_SECRET
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHanRvbDkrVWZ3MGdXRjQr
            N0NuNmozdTBiay95TlFiMGpGcVpSemQ0Z1R3CjhEVVkvcmVHc3puVEEzZFVFd0xt
            TmhWSnFudWtMUHc5czlQbm1vakxBZUkKLS0tIDk2b0hYOVZpejFPOGxQS0hHdVZn
            eThoU1BoUDgvMTR4VUdqVFRTaTZDM1UKmMohGHeb75pemRT328B30a0owFhAPf/V
            vRUgiqGthTGfVvzkUkxsyX+UP9CiZQjVlBcDXIXqQws2ie5iJpbluQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T09:45:32Z"
    mac: ENC[AES256_GCM,data:6vr31pa9VwPBf5+z8IcSXSlyMH4MelG4oO0+MHRLB6O9S9QwrtPVPF7vsr0ANTBk7Gy0qzOTUh6hibtef+h4zVGCoV20K+KGJtebnQMed6vYhVymvFA0rDI3P7HGr/GdncMwKtpPqGRUBSe9L5wKLEGDWly/cjwmnEdF/0IQkRY=,iv:qzsKHIgrl14EAH1az/IdIKxtrLngoiaH3L00BNuaKo8=,tag:kyNi4cW6wc45N5860dmgTA==,type:str]
    encrypted_regex: ^(deepseek_api_key|deepsearch_api_key|.*api_key|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
