apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-incomplete-dw
  labels:
    usage: qbittorrent-temp
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.1
    - resvport
    - soft
    - timeo=50
    - retrans=3
    - noatime
  nfs:
    server: 10.10.10.50
    path: /mnt/stripe/qb_temp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-incomplete-dw
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-csi
  volumeName: pv-incomplete-dw
