apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - soft          # Sblocca il processo se il server non risponde
  - timeo=50      # Timeout di 5 secondi (in decisecondi)
  - retrans=3     # Riprova 3 volte
  - noatime       # Performance: non scrivere access time
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-nfs-stripe-arr-conf
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: nfs.csi.k8s.io
parameters:
  # NFS server configuration
  server: 10.10.10.50
  share: /mnt/stripe/k8s-arr
  
  # Dynamic subdirectory naming: service-name-namespace
  subDir: ${pvc.metadata.name}
  
  # Set folder permissions to 777
  mountPermissions: "0777"
  
  # Volume deletion policy
  onDelete: retain

# Reclaim policy
reclaimPolicy: Delete
# Volume binding mode
volumeBindingMode: Immediate
# Allow volume expansion
allowVolumeExpansion: true
# NFS mount options
mountOptions:
  - nfsvers=4.1
  - soft          # Sblocca il processo se il server non risponde
  - timeo=50      # Timeout di 5 secondi (in decisecondi)
  - retrans=3     # Riprova 3 volte
  - noatime       # Performance: non scrivere access time
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-nfs-fast-gen
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: nfs.csi.k8s.io
parameters:
  # NFS server configuration
  server: 10.10.10.50
  share: /mnt/stripe/k8s-fast-gen
  
  # Dynamic subdirectory naming: service-name-namespace
  subDir: ${pvc.metadata.name}
  
  # Set folder permissions to 777
  mountPermissions: "0777"
  
  # Volume deletion policy
  onDelete: retain

# Reclaim policy
reclaimPolicy: Delete
# Volume binding mode
volumeBindingMode: Immediate
# Allow volume expansion
allowVolumeExpansion: true
# NFS mount options
mountOptions:
  - nfsvers=4.1
  - soft          # Sblocca il processo se il server non risponde
  - timeo=50      # Timeout di 5 secondi (in decisecondi)
  - retrans=3     # Riprova 3 volte
  - noatime       # Performance: non scrivere access time
