- name: Configure Cluster-wide NFS Media Storage
  hosts: hypervisors
  connection: local
  gather_facts: false
  vars_files:
    - ../vars/proxmox_secrets.yml
  vars:
    storage_id: "truenas-media"
    nfs_server: "192.168.1.250"
    nfs_export: "/mnt/oliraid/arrdata/media"
    content_types: "images"

  tasks:
    - name: Add NFS storage to Proxmox Cluster
      community.proxmox.proxmox_storage:
        api_host: "{{ ansible_host }}"
        api_user: "{{ proxmox_api_user }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        validate_certs: false
        name: "{{ storage_id }}"
        type: nfs
        nfs_options:
          server: "{{ nfs_server }}"
          export: "{{ nfs_export }}"
        content: "{{ content_types }}"
        nodes: ["pve", "pve2"]
        state: present
      delegate_to: localhost
      run_once: true
