---
- name: Configure VLAN 40 (KVM) on Extreme EXOS
  hosts: switches
  gather_facts: no


  tasks:
    - name: 1. Ensure VLAN kvm (Tag 40) is configured on Extreme EXOS
      extreme.exos.exos_config:
        lines:
          - configure vlan kvm add ports 1,8 tagged
          - enable igmp snooping vlan kvm
      register: config_result

    - name: 2. Display configuration result
      ansible.builtin.debug:
        var: config_result
