---
- name: EXOS - Elenco VLAN e Associazioni Porte
  hosts: switches
  gather_facts: no


  tasks:
    - name: 1. Esegui i comandi 'show vlan' e 'show vlan detail' su EXOS
      extreme.exos.exos_command:
        commands:
          - show vlan
          - show vlan detail
      register: vlan_info

    - name: 2. Mostra il riepilogo generale delle VLAN
      ansible.builtin.debug:
        var: vlan_info.stdout_lines[0]

    - name: 3. Mostra l'associazione dettagliata tra VLAN e Porte
      ansible.builtin.debug:
        var: vlan_info.stdout_lines[1]
