apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: calibre-web-ingress-route
  namespace: calibre
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`calibre-web.pindaroli.org`)
      kind: Rule
      services:
        - name: calibre-web
          port: 8083
      middlewares:
        - name: oauth2-auth
          namespace: calibre
  tls:
    secretName: pindaroli-wildcard-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-auth
  namespace: calibre
spec:
  forwardAuth:
    address: http://oauth2-proxy.oauth2-proxy.svc.cluster.local:4180
    authRequestHeaders:
      - Cookie
      - X-Forwarded-Proto
      - X-Forwarded-Host
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - X-Auth-Request-Groups
      - X-Auth-Request-Preferred-Username
    trustForwardHeader: true