apiVersion: v1
kind: PersistentVolume
metadata:
  name: hermes-agent-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    server: 10.10.10.50
    path: /mnt/stripe/hermes-agent

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-agent-pvc
  namespace: hermes
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
  volumeName: hermes-agent-pv
