apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hermes

resources:
  - hermes-pv.yaml
  - wildcard-cert.yaml
  - hermes-rbac.yaml

helmCharts:
  - name: hermes-agent
    repo: https://jyje.github.io/hermes-agent-helm/
    version: 1.0.0
    releaseName: hermes
    namespace: hermes
    valuesFile: values.yaml

patches:
  - path: patch-sidecars.yaml
    target:
      kind: Deployment
      name: hermes-hermes-agent
