apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-telegram-secret
    namespace: monitoring
type: Opaque
stringData:
    chat_id: ENC[AES256_GCM,data:tm+74LBfLgXi,iv:HEhR/fS85rNR1hQzVaDh39q1lYNt8oR/SizmYGJVlBw=,tag:+7RHpu1518Z3YB5cHmhnhg==,type:str]
    token: ENC[AES256_GCM,data:RgEeAd7J80N49ZVf1KvJJj7M3X4US4Tah69b3cHi7G4fmVEKQ5nhrbCNiihD5g==,iv:3MmX8cRz0SxlnKp/vceTCg03s422dpls2za5OWdbI50=,tag:NLUeYRFSCgyXND0BNqfLdQ==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJY1FRc1I2VGtZN1AxUklt
            S2hoczB5dnRKSXlkdE0rNDUrcmxSOTdzL1hZCjZaYU9Rd1ZTUGNXM21XYnAvUkRl
            bjNPL3VPYVBxZFVZTGRkTENHK2QrOGMKLS0tIFplZFMwa1JjNERFMWU4VGdvZzk2
            cHB1M2RSVkd2WjE3YmxyRis2V2NJSzQKcDpG41FhZ2k5EjXYJmrhoR180AetWhXb
            liEdZOfZP6kUA3lijuvn6+H6y/54o90iIu9OfTsjUIKpHCST6BQL1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T11:21:49Z"
    mac: ENC[AES256_GCM,data:ciMWrzZpC+kxwv1i2zGdS/4jUpCgPn5H08XBw7W5fIph32mcmfr1GwzrfXIyf9U1LKaUiwJDIUpphYI6aOywkfCIr+z0WUIML4Xhh1LsUXp5jWaB2K+ip4htZ3mWg57LR5UCLLstnQELuRrZbKSJfZwRWtYGWsOKPn5MN5J92kg=,iv:/b989VyUusL3nMtuOJAbPVwnb471NV3zP3WXc2ZzZbs=,tag:Sb0BnJmNUg+XBqOK9e3gxQ==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
