apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-mcp-credentials
    namespace: mcp-system
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:OEemc3rx0VJsOYXnskJtQjoUiXGaLn1lEXztECAyHDIaFivmQunbBDA9G75RZh/rM0mr4aI=,iv:KvVUtOYP18OEbhQPU6d7LQXGY4FJSX4iT+MBpQ0Jvmc=,tag:e32tuoiDJ72+IiNoNm107w==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybkw2MldySytMa0xINGZI
            YW9LcFN6M2hiNUFhZUcvTHhrdVh1dXppbW1jClFVZ2VtbVdTaWxTS3VXYkxlVUtr
            UDhuL3oxVngwQVBSR2JvVVloZmUwMXMKLS0tIGlmRDEwWkNlb0pzckNzSklLeG51
            TytISUVWczFsOE1xblhTM2VxZ0crZFUKiBPmAhYf5YjLnrTh/Q0z+zlGCMwLrvl6
            dhm0kjQHumAG/D2YnygyQh1zowWtcJFw6XFpQmbBCc/0mhiX56GkBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T13:32:45Z"
    mac: ENC[AES256_GCM,data:VaDxxqyWr9q/ydiJzZEdL65DS7wYVUmrqZqJlpSgbiWAyRKeThro8T4EW9Ss50rkL8b1xn3RH78SN5d37gaP7Q30DK3XDiqsl0dhXyM6i5S2LteRR1BOtwlUggk8f3GwYWa3vghmXJL/KLpBdaeU7uGTSveBwrBx5dEZTpDcNu0=,iv:3ouVbTc9yX39JcqfNerceVa4JdWrWTEZNnBi4bQEiBU=,tag:8yL6UWAPCRi8IJl0NBtiww==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
