apiVersion: v1
kind: Secret
metadata:
    name: filebot-license
    namespace: arr
type: Opaque
stringData:
    license.psm: ENC[AES256_GCM,data:CVdZkg6w05jqqd01aEEV0nhLaT8n/uzTg5ua3z+fQzk2+yKgeGijIBYyEKZnPItZP3E2HhK8br0Q57GWTGcraK2CQbju5l1x3fNq+3Lb/GKqfiGsf/E3R4Kp1IicvdPhIn4Qmd/VjfVaTA9ugMduReLgicoQMnjE+1QHb99JbmHmiaurna0UFHeRbwx7yFZEJ5siMOBFhZiaaygWYpvjBYp0k6mWeqoM2Y8mnZL+F2Bol6VmewDtorNg2smwCWT4IAU3F9zWXwXHvGWb0bpFqfWj7rNhzbq/65dHtsJCqvMdJlKpAxTB7CgHquRff5WAZHE7tsXl9ZD6QvtVK4xiy4+ETOrkZmDPr6SfdgAPndG8a0/ntD5fRX23vOa66TLI1oMrbDNJ4KnXlGcGFbZQ76fZWObq/2hwRnM8mwVpzddN2jMnjy5RXIr0w4rkwE7rAjCL2mZQb0tKy6jtkpkjSGCz5H8huuMzTz9XC9WyMi1BLpnBv332HdkUnDg06SCIQqNc9Ou30o9ZaOE0dcYJlyRXFcSdEZ0THbB/fwMoqHIl7Gls7GckIQQEkqA+OVdlCBoYHH6HoxfKhpqaCMIhnAORYd6g2ivNFEChsDZ/mwEtzC94rbY+eM6/3oYITRtmdl8lbIZFLKVOcNRmPhM3KH9hAR+zCAtVz7Qm9ion2doUv3canWJhpc1YcUgJ2USKLSvZsrVwQ8PQ1cCR5iZnU1CmL3vfNTckRQ9Vmcpp2Bk+rdeIgc7IHZU+v6LWKj+xuGwYkGOF2O75PWtS/qiPvg2D7hCZ37cozyNuuonQ0eE5t5979Z6+Vzwcc80bpiM70n4oYX6giSJ4L6JQtOoCNR+6TStBPqMVKGGl8Uw=,iv:ygbzjXKV0IfHI0+++9yfdtrf59/4pVOYYCH7OdJ09Qg=,tag:ICvC9FpVvF/VodM5kUK/Xg==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRldpaFZRMnpmdnE4Rktv
            dUdWY0cwaTdzRXNoTEFad2tOQXBRd2dhQWdVCmxYSTFyOW5MQ1FacThFcHp2NlZ5
            UHFaK3p5d05lTnFhMTVOSXd1c1o1blUKLS0tIG1IYzNkRlppWmIxN1drbDVNVDc4
            b002aHlrUE5iNStSTmtpWXoxMkdxMTAKiDJ6b7evp3+/MS1eqEWqrJegWzsOVDrp
            I0gawAZTj9khi1SJCJu4ph5yNASA1ayRzPdjYYwKCNN7jUistI9OcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T19:14:47Z"
    mac: ENC[AES256_GCM,data:PgTiUOm0b/grQqxpcfezzBwydkduDgsw8wALv0Tp6f6ZZICJA0z2RAkdNN1ml+7CZ1+8R0+J8zdcq5NbZGZRFH8bZmM9ImfvlyLp0VC5EgObu9oMNdvkLGBHWVsUbowaqdhaSxPIGGcdlypNAc2GV3pJOEApPFXBqoB5I5HaE34=,iv:FZcJgcHHiqgMbcin/gcUNNi8NTjqh6uDmygUGs9Mkj4=,tag:NRIY4qoIkXyiQzEJtFOyZg==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
