apiVersion: v1
kind: Secret
metadata:
    name: gemini-deepsearch-credentials
    namespace: mcp-system
type: Opaque
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:hX0d+RV6wUP/P0zhFBE//SI/V3YWTMPKycD0ThX1wUJykfPO2wYp/YZjG82cBcjXFh0Pynw=,iv:LeOjTCokfvvTHO8D5TPy4Ysnw+SFIQWC+McRRqOQEQI=,tag:UbT+kWNcVuy8972uGQ8HCg==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNkZNdEdhdEp3WFpZYzcr
            bWcvc0JHT21Pam90SkhjUGNuby81aW1CK2g4CityV3RFUFZEUjJFQWUzRld1ZldT
            OE9aUkNBQmlUSmRqbXlac2lKb3lOT0kKLS0tIEFVdnZpVkNrWkNjN3R6TFU5SWdH
            ZUVKb21YM1VTM0MzekNTOThGa1gydGsKWZaDRou0g0DhaiBfR4EIpH9FPZz7cmT3
            DyILopqQ7IqwmuRDt6sOv1o15YiSbg7DRKFpoNUYlns7zOu9iQSk/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T15:10:00Z"
    mac: ENC[AES256_GCM,data:cGFlaA0qigLjDGqKB721Zf/YMdeIquksaoLWesMhyPTda8P8tqT7Ag8OPG6k8pGAdxslfY4eI+IQzIhzKhBbVIXb3mVASodaa/opJhiJqZhg7zUVXKg1s9n6hFY6D4v3gjE8ECPHftP4Sv+qam4LjN1xmr25kaAzheYZd5Eocgk=,iv:RVA2gYZRxpl18Sl2wjbNzXSan7Y4tDL9PAXjPfvpApU=,tag:0l6DXbDnSykTSVVnYk6whg==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
