apiVersion: v1
kind: Secret
metadata:
    name: github-mcp-credentials
    namespace: mcp-system
type: Opaque
stringData:
    GITHUB_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:a3ggyZPF87e56V8C0ELZQ5NRHe/YGNJUJuKJAVOrXuPSzYKCaR03nw==,iv:8wwbkZCbTpe7A6a8p0BELlFgbn4/kldqtseMgReemmY=,tag:C1yrPZU1mfrAXU1D/UQPJQ==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aldGakZndmFBN0laSUlF
            MU9GNm80TGl6a3JCazJkWUpsWTR5ZTdLbkNvCk14RGdOZEQxN0VYUTBKakI5R0Zu
            aDdQZXM5RDdvRXhaUTdURkVZS0Ezd00KLS0tIGxWaXdDQ1Era1hCTzR3RkZPSUdz
            TXhpTGlhRW5TeVJHTTZ3UGJBa2JGUWsKhAXW7pCgPBplubmkLq6nhUDt40d9YBab
            Np9RfIhsz+5KVy5ARZjAP9/dYaVnyMtb8cft4p4JvBjh4FagbhYQ6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-03T10:16:31Z"
    mac: ENC[AES256_GCM,data:pU88xeDv2sBtX9LOakF5g16F773f3+C3QDxATiqWGFbekbdZjawrkRrSkHxgNsJ53X2yAHVKZB1DWl4SfUJiDhAHj1YbQKXwtuoaEbHjih4U5t1T/c5Jq+rfyjOci+07JsY0EOcfWX3+Rhuy90I2wbCt3Rw62HJqLoRg4ntmnYk=,iv:IuWWF1Qatvtf4B5XewhYn+LSjyhtxGWhPz2OesT2E30=,tag:C7RrG9j04xLbI6HAkDi3QQ==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
