apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:zkbT/l4=,iv:pMxK5ltyVFoK7/XDMd8f7OMY3py0CggmEwqHbHoUSEs=,tag:sYD0X3AL0In7Ca9WyNom+w==,type:str]
    admin-password: ENC[AES256_GCM,data:XZsofXBsJl4ixogZjw==,iv:CZuc4WkBoAbdo0jsR3/hpsP1hCnufSDrnUxwYk0ulbc=,tag:G2vj7IpMOGS/Z+XyowcPWg==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHeVlPdzlLeTIvMXp4a3RB
            eXl1ekJveXdneStVQUZGZGx3cVFZTWVvamdVClY4czMwdS9pc0JSeFpUVWp6dW54
            UTBNWVl0dnk3c0JkUEh5WlVraTdZZVUKLS0tIGVuRUlFZVJnT2R0Mk9oOFlCVXBl
            bVlPeW96cXovN29zZW1TOUtCdFcrb00KaUnMz3ivZ4Ih0o/eJSliM1uPKwbdvP+u
            Jupm6f7xwsBUQSZLoFJQJN1fShoQEt9CmHpd6YtOfmZEL9d8Jwjjfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T11:21:49Z"
    mac: ENC[AES256_GCM,data:GmemTaqm6RuF79pgU0BVNrJoa6DmyiExvJT+T3ROwNTsxJSvhPbBw8Lvk/xkEtaRz9R1lei0l2S41nvjv3RfirKW8KlcC8L4BAI1RcQiUDQi/R3wlFks7mrJ+QvnYrJxB6y10N5eZr2d4chShHJeO8P0pN242CWaQD0oYnQFdrQ=,iv:l+gzXRU9dsFCnfy4qOSswqGtgnnZh6JJHwrmnsdUvdI=,tag:J2RZpYHOUV2eV2bMt/Fj+A==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
