apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
    namespace: hermes
type: Opaque
stringData:
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:krfFNHs=,iv:doqoyxZA12wh7lyx04XahtH1JRSjJ2USlowFAKYYZp8=,tag:ygih60Ijua0WkO4mUbF1Jg==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:a6rY8W53h8zr,iv:YiZw8FpLI7xQPMYxm8i+Lb0gYnKO49bUO+c7dPepXlA=,tag:sa83eDgntKLQT1G5Sab97A==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_SECRET: ENC[AES256_GCM,data:E+XrlxE2oGG6/OPGLl++bd/C/DIEIlQTNyaQuXsV31VY0Z+6fUagGYoRG6Y=,iv:cTp+IY/Twmlc+0Gyb1WEcqVLMjWkQ6N7Q3j4LdpzRng=,tag:+4ISDLFUDH9COncKXxLvRA==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAya1RhaXlQWUplQ1RDdWVu
            RVlnUUt2T0QrWVp0R1NLQVhndlVRZXNQR3dNClhyak54WHRGK3RWQTRuSjM5MWlo
            cjZqaDNMK0pVMmFVQUFFdEFLeHhwdmcKLS0tIGtGMVZxak8yZUZhM0RIY28zMnlx
            Z295NWQvNS9taFdsbGlxaU8zNE5MY2cKz1WgnfRckIuuqRNFFY3c8gHUaToYsqd0
            EcSek6jaosTDhCbRVADWt8EWkWqOac9zoux+2/8zLZ/gUlsz+zsncg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T19:25:44Z"
    mac: ENC[AES256_GCM,data:gctNXq9x2Z9FgJPWkDCX/GrQWdy2lkwPZp770QTEVT6w+Vrnijy9qTvOG5JpVoPiYPzgfgPciUvrtdu/YdIW/M1E9Mo9azUBjATDqyPSwOYWrQOGdn2ZH7TFCg8QKuz15Ao2F0tSCg/4pF3V/WTitrw2Nado4izABxlTmqfG9S4=,iv:g0TM1aFwn5DZ4J3+N1YLwEUsddlBywpQwF7r9xNz/N4=,tag:dDLRkjwDzjqFYuchmB6eog==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
