apiVersion: v1
kind: Secret
metadata:
    name: homepage-mcp-secret
    namespace: default
type: Opaque
stringData:
    HOMEPAGE_MCP_TOKEN: ENC[AES256_GCM,data:HqPcCHD3q1LY91BxreJgQZ7Q5I855zs2FShChCQ6tOEg2kFQnJ54/iE1AzbJKdyq,iv:TLkzV6Gj7k8PBYGmz7TVmW+fd38ZL1rixv2J17soxZE=,tag:tqmMXnhfTIALf433dEZzaA==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVXZZMThIRUhqSnRJZEE3
            VVp0ZHRQUXFWci9BckRLR2lZZ2hGSmdpWnhzClI4Y3JES3VCUlRMYmV6eThOMW94
            Znc4MXFEVVJCMXhZcm9nYjBTNkcvWG8KLS0tIFhqdXpjZURJK2x1blJONTRCbWNm
            K2xxK2JVcHEvakhKM0hYdVhzU0lvUVUKdT+Iq6bzo/qkoUwYNO8NLKsQ+FsvB+6P
            YVGFIiC3qGdHCPEJ4UpBgaaU0CZh6JAM2FOyxm6K9xsO9qw/18Uvew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T07:22:43Z"
    mac: ENC[AES256_GCM,data:liHviQIEV2gvwF6/KLr5QW0AENmQyR6Gi5d5+Dgn9DKBUG3dqm7R/gG+UULZCvHcVtSFfN+ZbphAHDig3D6ynqLkt/jbd1sF4JpaK2pymNHXVMEB8goj6D4lVfOCswPwWiqzA93YsmbReEnvFJUo4CsLj+J2BNJJh8xUfHsaCNg=,iv:JstS8ZK+rH48giaHChWZWNILL8Q3pSQ8SHp42AHje8M=,tag:tzrhCBZUOm+VNwKARru8OA==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
