apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secrets
    namespace: n8n
type: Opaque
stringData:
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:zOHiasuP7fEclMSzSCcnj2kvRGPe8yUK1ZNMGuGWLhXP6s0f/spgAsyztz9bFpTtTYyZae/BvFo1lOvr5Pi6WQ==,iv:/IhonU9N6L7TkcfwvlJLhDmkfcoWhv3JH5+dBVoXNU0=,tag:KrUFnC8kToXCoqSKS5d/bQ==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZksreUlYaVpiSVFZVHdH
            ZWJ3U241Q2d1MGZBTEc1QitwOUY0SVkvb1FjCm5OSjBFRzh5bXpWdCs1MmN4REZQ
            K0tGSlo4bDJ6TnhOaVVFN2h6WmRpM2MKLS0tIHV5dTdSYXMrdUVId0xZVW5ZcEZQ
            SDJwd1FMdEFySXVreUJNTjhxNitqQTQKtGLwIanXWY/XS7+1whK7RbZE6VuQ8FNc
            f6yYtuT5FBYvlv5XjiFPXwuWfl9C9r5nUJEL166UWJh7wNLrZqzgPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T11:21:49Z"
    mac: ENC[AES256_GCM,data:SP2zJc2qtYuCA5QpcFhosYUMMihChE5rG8NT2IrgvlmXCmtzOe3g+rFoL34EA6syEcHLu5+IPCKJN3DHqEND33+u+g3/amKpjfxSE4BA6oEIMjEW6udN62rxZfcyQbSCYWgYmcDurFklCUuCEMG8PUEE5ooImY4HRkKmB1Hq7Qw=,iv:HdVdvMifsot2fFVfcCu+fyXBBcwmimGH/5lPHVZTpMk=,tag:tAJrWr7xa7gZEqsf4rM4ww==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
