apiVersion: v1
kind: Secret
metadata:
    name: nowaikit-mcp-credentials
    namespace: mcp-system
type: Opaque
stringData:
    SERVICENOW_INSTANCE_URL: ENC[AES256_GCM,data:j/EMHKn3+AOwKuiLSnFuncmYb7CCGJcM37qdju1Izbu2,iv:AKvR1zGmMVINDwNHXxWSh1Sb+33eJg8SkA1tZgcmRB4=,tag:qgsKyMKxXUXUoiQwt0PcFQ==,type:str]
    SERVICENOW_AUTH_METHOD: ENC[AES256_GCM,data:4O/0e3w=,iv:WbHWTjEA2HZi7dXaLrDDoF6JxVY33O8ayePbFqEyUi8=,tag:SrY1f5ohAzfQhI7AWkdJZw==,type:str]
    SERVICENOW_BASIC_USERNAME: ENC[AES256_GCM,data:huhxna4=,iv:9baAq6RgUxVracxfVAoIMXYj3ppR1AC5boy521qODFI=,tag:u3nb84Uo9Es2p5jooUt5fg==,type:str]
    SERVICENOW_BASIC_PASSWORD: ENC[AES256_GCM,data:vFu74Gk/+9T1XIScelv1,iv:iIxBSGlfnFieon89C7pLuQSJEiRijsKg3BhcVf3rqcI=,tag:rC2syx5jpzszGdKipdRexg==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3emtCS1NodWxVQ3Q4ejNu
            ZmhvNjA2enFzdHRPSlRvZkdRNVYxLzhsYzNjCitMY01iM2FVbFhTV0wzVUY0Tm5o
            R1M2UEdJNTFISUswM21Dc2w5cTJtMUUKLS0tIDMxM0Ywc0hzV2tBUXltN1dlWTlE
            TGNZMnJPTTlwd3RUVElnUXVQNmVVOVEKyJlrNjhzFLZWyJDcWuchZtZryIsstItg
            tPOr+xtu4aLuCoiR/xpredEALD+VH48UhSd8Q/aII0BwSEMnABVmtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T03:32:04Z"
    mac: ENC[AES256_GCM,data:fzc3RFk9QuBNmBKJX89+C2fnYq01Ondz30+0N2hG+2DZiCmsaWwvZQJNqwkwRw6OI2yDjDqReAAWRA5hyH2gInHGKfSCgphDflJwpWAnRxGfSjbgGjYr/bsHFGSDQOAjq7EHI/3p2uoBOGCvTOPFvRLico5al9YXxECGriNAv8s=,iv:K5Y6tDdV3AsldjhJKYan49z9zTy7VppMG+r1PrGHcRU=,tag:rJDBmBaLYCjR1RzwRHQDIQ==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
