apiVersion: v1
kind: Secret
metadata:
    name: nowaikit-mcp-credentials
    namespace: mcp-system
type: Opaque
stringData:
    SERVICENOW_INSTANCE_URL: ENC[AES256_GCM,data:I797OzEA+f+loj8+M6juz/+oyoi1pCBn6IrOnf65O/F1,iv:6nUiq35QyNTkge4or0r567tNXWv6rGCg/XgA3pBHeEU=,tag:yxWVKc3XMHCDuUy+QxEwmQ==,type:str]
    SERVICENOW_AUTH_METHOD: ENC[AES256_GCM,data:i+xr/+o=,iv:5xhcbTd3mCk1/g27B7a486KByo8fy6vV3tI5+YTvkbQ=,tag:vakHM+Bb5cHpXbwWlggVOA==,type:str]
    SERVICENOW_BASIC_USERNAME: ENC[AES256_GCM,data:hPBBDLU=,iv:F9vl/5AswcSGm7ce3cz6EaiXLTvdfBrWDiXqPgyhEFI=,tag:/UJLCly5jA362xx6Laf0jg==,type:str]
    SERVICENOW_BASIC_PASSWORD: ENC[AES256_GCM,data:Z4FgYa17S//IJhh2,iv:0Zds/CDh1+a5VeZo8eVbSn7GxB010VWoj78sNRK+tQc=,tag:kBcAW9APiWdhQ6gGk73NQg==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZFRBNE5UbFYxK1U1QkpO
            TzZ5cjVOS0NuUllTMC8yZDFrcm1SMXorOVM4Cmxmd2Z3SmgrZzgwRC9sQUFTczRV
            TUFKL0RTTDNTSVY1NkdGNmc5elR0Y3cKLS0tIDBjelN4OHFCRWZWZE5zS2NJdkk3
            NHRSU0NMZmQvb0dnWkNJVnlVT01BWGsKri8hP83ERztDGJdR1xTaImBEPvS83B9+
            T8F0ZzSPSsKsZ26Z+k3OdXVjWaaCITypiQNAdhjzcJEp+IjsofsU2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T02:58:02Z"
    mac: ENC[AES256_GCM,data:i/gEvuVVA5p32iun4EDJEztjD4GGQAr05mJg82iuaxgKWHJfpvrLnRopcIcckeebwoSziXV+w/Bti+nb177b2ltIMJ0/M4JnrUE12X+jeLBDLnlUVjbbRwJ2tzuHj31r/dXNVY4vHCmAMWhvZugiw8n33iAmbRixsephqdKDIuk=,iv:ROKDEHU3mV+NbpiEeSldNXx0dpxYeQeoa2BeEVZwS9s=,tag:sXOvfQvpsWtmZh/xkGIVaQ==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
