apiVersion: v1
kind: Secret
metadata:
    name: opnsense-mcp-api-key
    namespace: mcp-system
type: Opaque
stringData:
    OPNSENSE_API_KEY: ENC[AES256_GCM,data:X+b5QIEwRRqbU3gMoZcisXXaueH0ppHGiV+mGn9Cap8ZH5NqBuYbgIi3dgjfc6g55QXK4Dm9g+9xfGzGYMgcwnwrBp02jdUYd6rs4IkXGp0=,iv:X+v0ISI1Vs1BbgdXLymmracqXMAv6wwov1NIIGhmifI=,tag:oR9+YIKQu8THyOO8W9qY0A==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRmVyNStKWGNwQzlHZGgw
            SzdJSXRyM2hEbExFcnQrbXJ1VlpSSEFadUdRCnExTlFHNjFEVFNWQlplN2UvMWd2
            TUxSUHNtLy9nbHZzUU55ZnFVRGxzcVEKLS0tIElIaVZKRWIwNVdOZmNXdHlrRU52
            T2ptai9ZOWtEZDFJcisvVHo4V05qakEK42ZQARpcgcIHmN7f/bxKzHOsFVHBdJv9
            NZgLL6mXiCcdxnAT9iXmCqqyG3RnlEaopuVX/er//E0s5vXQXePA2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T13:27:57Z"
    mac: ENC[AES256_GCM,data:8QTqKlF/jeYzRR/dBFTwuFrYNwN++fTcMmRDjj9rmYOOnxQNtx2BaXyoAS7n6D7hQCI9r0RvOgD8P+ECFokkHXIwF15hQAAy6BQgLXqdvx416UOJ8OR0lFH2e/2+fvqXzbmezJoAx3eJwxvTXIBEINeMsj/AGjnHZmxrVfOEqyU=,iv:3T8WbJwB8nBI3quqnczikxTKTXluBB5EriSZk+6wUXM=,tag:As0mxYvnPRJAXvAyeeHBQg==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: opnsense-mcp-api-secret
    namespace: mcp-system
type: Opaque
stringData:
    OPNSENSE_API_SECRET: ENC[AES256_GCM,data:oOb0286lcC1WV5/IPNTi+y1KPXCVtZAtUDENq1gQ2GQh460hKJVlyrQuwePg+RfTfrXY1ocV5bcU0csE15TPOkF3N4Z+SfQr8L4LBAevWnc=,iv:9pP4jLE5rCjYCJlXV7wQqv7wGXLrua9JkPyXzVkzy3E=,tag:4i/qLwqIjUD4GLYUEJOMhw==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRmVyNStKWGNwQzlHZGgw
            SzdJSXRyM2hEbExFcnQrbXJ1VlpSSEFadUdRCnExTlFHNjFEVFNWQlplN2UvMWd2
            TUxSUHNtLy9nbHZzUU55ZnFVRGxzcVEKLS0tIElIaVZKRWIwNVdOZmNXdHlrRU52
            T2ptai9ZOWtEZDFJcisvVHo4V05qakEK42ZQARpcgcIHmN7f/bxKzHOsFVHBdJv9
            NZgLL6mXiCcdxnAT9iXmCqqyG3RnlEaopuVX/er//E0s5vXQXePA2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T13:27:57Z"
    mac: ENC[AES256_GCM,data:8QTqKlF/jeYzRR/dBFTwuFrYNwN++fTcMmRDjj9rmYOOnxQNtx2BaXyoAS7n6D7hQCI9r0RvOgD8P+ECFokkHXIwF15hQAAy6BQgLXqdvx416UOJ8OR0lFH2e/2+fvqXzbmezJoAx3eJwxvTXIBEINeMsj/AGjnHZmxrVfOEqyU=,iv:3T8WbJwB8nBI3quqnczikxTKTXluBB5EriSZk+6wUXM=,tag:As0mxYvnPRJAXvAyeeHBQg==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
