apiVersion: v1
kind: Secret
metadata:
    name: ragflow-db-password
    namespace: cnpg-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:yxoXz5mPvw==,iv:xBDR+LE/anfGUSr68B/coBzW/rkRvrEq6GhnulpHwao=,tag:oX4a+yKtEI22Y6Xp0P1F8w==,type:str]
    password: ENC[AES256_GCM,data:XjCqYYp/z+XgNJlDm6GJB6caS/9vy59jSte45QcR,iv:8Ne0ZFhfKzvLbt6wVkHYz6kcOfBuDi/F5yUOXTWR+Bo=,tag:oByBXzwa/2NJqYksXLr4pw==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMW4rdjNGVXhlbG82MStJ
            QkpWT2Z2NUp5TFZ4Qmtua2NNcWtaRjVMZmwwClpPdndkYnRiTUtpMHRlK3FCN2Ns
            MUJRSTlKc2pwb3ZrY0NieGFYckF0OVkKLS0tIEl0bndXejZKNUlESUxkMWRSbWo0
            c1J5R1VlUjlqM0JKK3lYZXp3SGpPQTQKT6mSJ6muBbqIEhjJC+MtcThXgH1CbWUW
            BHwv22hb0EbhLuCrzEi2wNXA444+jcCQdLyZYL26WO7BWSIuLv+vbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T16:13:29Z"
    mac: ENC[AES256_GCM,data:MZDMhdWG6ZuCX3biMctD9uiHbsQIiH9NiyJPlT99nyQLc8KO81no/8lxMqTMGrSh90ju24VHPY8oS+ND6M5M/YTdsIrGKHO6kJRxkKNdoEtLmA6XGJ2osJIalFvRpY6BJwfjFJPG0ix0DW/NuSD8q8ixt0+axttT7uRhOLgR5+A=,iv:LxPG5aMfoLpCj/5dc+cS0JJ1uEghBl267l2akdnGEiY=,tag:ADZLaNhjyM476JLK/fZJqA==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
