apiVersion: v1
kind: Secret
metadata:
    name: ragflow-secrets
    namespace: ragflow-system
type: Opaque
stringData:
    DB_TYPE: ENC[AES256_GCM,data:yc/0DPQkZyE=,iv:lXavyQDs8SF2SAuXAsjocQBJzKIFeeNNV7GHsIBnw5s=,tag:KkWCyPFU49e8+Y9mp7AMfA==,type:str]
    API_PROXY_SCHEME: ENC[AES256_GCM,data:JT3+TdDA,iv:2ekSkw9Iuuve/p4CGrGcwCYKyTI843CJScK/N23leA0=,tag:qly6IWeAoK1rIQHGJiBj9Q==,type:str]
    STORAGE_IMPL: ENC[AES256_GCM,data:64ZIah0=,iv:4zK/7LNXYtnBUfXRofcSghiYeWpMJJtD9uRP0d5Ofk0=,tag:7dl7pSVZX0EQj0zvrNL5Fg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:2QULmWLvoH8=,iv:4d3+piIHmpHmcItizZg6lLK080vea72CAxwDN2iLWBU=,tag:cyTLzSDsz2+Yjd7dTKuqxQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:mJQ7UMLH2w==,iv:bZeGVy60ec3xqS0fsrO+E8/reNbJn50F8XL13qb3Lzo=,tag:iTD5W9fsK4qVZeoc/pUkwA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:WM7mA1tdSwHREUkPak1NsLnZ+ntgXWqSryLxX1PO,iv:Sh/opdb6L3AknWJnUyJM/Op/fu3vxpbd3GpxiCDpyZQ=,tag:jk3h00x71GafjPSizrP+0g==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:fM4J0KkRmNt3/seJdNOYfuB4RHbFrGhFweQzrMEvwNOLVOS+3lUiLWDg3BB8gA==,iv:7xmBPfZOs1nQgCgMvlwW3RobUrwKho9vk4pY+HSF+h0=,tag:l8RTB6TXwOp904wCF7v69Q==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:8fdmxA==,iv:ghaMxboe5TbhZ98gHuV695zXczG9gN4WrxcLf5uA6aA=,tag:JRt5QiRoGL19uryybXL8jA==,type:str]
    MYSQL_HOST: ENC[AES256_GCM,data:5GJRmLTrCbRNRzjzMuKRNmg4i6OY+gToQzlZwr+I8Flak/yqw9OGQ2gLr5k42w==,iv:D2iOyJ3nqfBohFn+QbTMWhLuhHb5kXU5bQzeOLSWbeg=,tag:NrjLH+p0equKPuOYEDdWzQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:uxyIHAzpRyPV7xQ3ucPc+uxW0wqsAbgw0iamp7Nl,iv:kxhmV41tR3XQIM4dg2roIMySB+ty2DuZzp28e7ZKYRU=,tag:zyfTA5Db+qJo8ZkpajOLBA==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:wFfCYqCd/eNwPQydpzYS7TzZRIidu7J9jw==,iv:MvjFWbB5s5M82QTWCnDZGdqGP0iHjZCCfRDyVfosFhw=,tag:IpRL7/0VIiEOMkvkbF+3xA==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:neovhUIjjzpMd5KU,iv:HLWkJs9zKNlAxwBf6HfF9MXdrhKyUWWphtGL1OUzrfA=,tag:rIYaNnBb/y1jhU3ZGXXs4g==,type:str]
    S3_REGION: ENC[AES256_GCM,data:BH5UchkK,iv:b3gKWliDN5vjczJQ573DMdmJoeEWy+1b1sfWuoIH+uY=,tag:Q3oHoJTJ4p952y6V1f8Nqw==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:hMUFi+Mi85B3NrR4dE99jA+SBIs3AqiEUYE=,iv:qujwZ6SQPnbqSg2M1iMjKXCelpHVtiyqI6SuobEXMRI=,tag:NOb6J0/1yatr3UT8bs9Fnw==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:+avCzdWBRO6jsKTa9u56Xh9zAdOPat5zgu4SEah89KZL+idICV9GOWfPwY3B0WHTCTf/+FRXR70IYEpA9UAn2Q==,iv:Q3EcPkkRnm7k27JR0SWbgILXUT23aoIjusyya+ZwJO8=,tag:F2evXrlqeCusNqlSGP6AxQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:/V4x2FmwQ68l68cyzbidENjsV0Y70QMaFJrb87Q=,iv:iygkjMP8+c1hEFWI+uTz8H/jbVkqKcoww1F0LA/WtTo=,tag:IxnNPKfcyWId3JkfIJpo9A==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Zi9rbFRsSlFWdW9KRGZD
            NnV2elVmdjUwSllML3dZcWFjTmhNYmRnMzF3Cko0ZzJoMXdtVW1FUUNDamlaeExw
            QkU0K2dWTHlIZldQUjg0cVQwK2pDSDAKLS0tIENORzYvbWJQZWZ0UllwSlBJU016
            OGVZYTd3Ty9qUmtCREVCU3I4MEhDa2sKXGSCvwRP+Eox+8Cw/T/VDIedCKU+ZxxU
            wOkL0/XzMbJmLtct6acVRPXJztotNpWX4JgW3vcT0dEatTLuterifw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T19:10:39Z"
    mac: ENC[AES256_GCM,data:0J4rkGBiL52HamwWCstud0ahTUJD3zo+BysXPLeHfFkmdVRC4+DrAWWjx4AYKwsHazQl0OoRl72r5HDDeQtSPKyLB3eaT17fC0yQ/e+GS2viU8H2BR93HosmFp/IUfhAkAA69qkAdEGibDV+Q/AIDaSr321ut4VdTfcVhbsL5rs=,iv:NHJ5RmktxS/WJJUxSWL451E9OXmIX3aZoBCwOikFnrU=,tag:ETW3pK+6KBzeG4AigY7ZPQ==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
