apiVersion: v1
kind: Secret
metadata:
    name: servarr-api-keys
    namespace: arr
type: Opaque
stringData:
    lidarr-api-key: ENC[AES256_GCM,data:PvSLYhfGxdlSCD2vcl5/eH4EhiMKa9o2+dATOcb7xjs=,iv:D6ZoKSIirsngB4kr9uqo1jQ5Ccm3s6NLpQK8dOOt3ZU=,tag:AnHdVlCKORIeTjsv4Y95oA==,type:str]
    prowlarr-api-key: ENC[AES256_GCM,data:Kdx816tEjDi3U4ZxmnwLr+iRkOSUncckURhPTfdc5T8=,iv:FwohtoUQ0/uxfKA77e23L5i5aVnLQaK3yyHyfblpMno=,tag:2AfUpwkDGZ7hLN/NyiQb7w==,type:str]
    qbittorrent-pass: ENC[AES256_GCM,data:WVM3eTJT8W8h,iv:OP7IgXVACb7AQWrAsySheL8J/wU7gnBkGnUDrYA1ZeE=,tag:aYs+efvh3Gwe1Zy0szTbiA==,type:str]
    qbittorrent-user: ENC[AES256_GCM,data:FusYu6Q=,iv:XyEDpuqxHZx00CYRKLT6J4/OWLnNb1nWb/rsSmdwbik=,tag:ztKCOiIA2nhDxzov7xSnBg==,type:str]
    radarr-api-key: ENC[AES256_GCM,data:b5TjCNK1dAYv+AejMySkEVpFwjfoVKaKhXnpbUWHyJo=,iv:5JzT97dwoeenvEEEJmQqPCmWYameITHwCJ7gXA9r3qc=,tag:Qla0lycJrV0MwXTwbQXWyw==,type:str]
    autobrr-admin-user: ENC[AES256_GCM,data:jCcVFmE=,iv:tBZZyetcyTMmUoQF5i7wzmYZFR1QoxGrxHEjlQhy2Co=,tag:hpcKkkpKcxA/LtnTCSBdkA==,type:str]
    autobrr-admin-password: ENC[AES256_GCM,data:RFZ3exl/XBwg,iv:UptIb/wgu9R3+/aTHx2RVznSpYc+wpUbsbccjhmQ7K0=,tag:OQnELwNp0Xj3byMlroqs7Q==,type:str]
    telegram-token: ENC[AES256_GCM,data:0HQMQ3oJ8fpRhkQ/ZtVXXrJ/y5XUjUDlR9O5JzJrik/aZ1yeEKdQDTgNe8O/Fg==,iv:cgUAz7EZwZ89HZLGeG48mUve7NEmEJS0l/Cgx0/KKsU=,tag:nNYixCUFyu7M+F1HIywcZw==,type:str]
    telegram-chat-id: ENC[AES256_GCM,data:CIzqBFoLXKwr,iv:MhWCoFGM4CiTG5HSEYxtHjhcoNf4CLVS/WM85U8ji3Y=,tag:6gQboU/EZKc+53RRZ7Lm6g==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUFhsbkl6aXZlT0pDd3Bm
            UFRDNkJqZHhpaENXeXVodm9ycU9YZ1RaaXpzCm82WnovanFyL1FOM3g4dk1pSS9k
            ZU5qMXJsTElPT3l4RTFnMWIwWnlEWFEKLS0tIDdJU0ErR3hNSmgwcWNRNms0Wjlh
            bS9QTml3KzRKeExxRXVwZkxsb1BJTG8K09SGqxi3i6rMzDygcyq1aKsEuMDng3R+
            EPTKt4+IbeK/lMIJ4ttfZz9nQsZuK8G8ZpWSWUjtcILoJ8Gh1A/u3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-18T11:10:50Z"
    mac: ENC[AES256_GCM,data:gbfGGvIyzO5LvzMLBrHKGkLtcYELpqHaeuE6iFAChGldFTemtzDUHXWUjTsfVP8NUNEuhakgJYn6OPGJbfMFEiTCZ1GSKAK//kK2JXs9t4aoCgww7xHJwpj5/MK36IXJCIM1tHIRJ63D2uPsjiBgyY0VeHYNOI91X3u4vegZYm0=,iv:Qa9WpMTv+rhpH8SxTuqc9CZeOCPMPjphXFX9wvWU+vg=,tag:CyoamDENRbew2LCC4ZzclQ==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
