apiVersion: v1
kind: Secret
metadata:
    name: servarr-api-keys
    namespace: arr
type: Opaque
stringData:
    lidarr-api-key: ENC[AES256_GCM,data:pBQyokmK53RSvAFd7FyQI3swxhYbnEGq/iNmyzHe2Uw=,iv:cztKwgrpp16vfpLXQigqEo6zo1nIcoxhQROUMEW9oyI=,tag:X7LL8460Sqyq74QKwBcPFA==,type:str]
    prowlarr-api-key: ENC[AES256_GCM,data:yGBTeDlDtdc3jyj4tFHUVgMGmMQfZvSh0j65rkPLUXs=,iv:QQFv7wB5BWy959F6QnBgrAtaTERyXwmFaGc0yFeOgro=,tag:2s5UsblpSW4AaI0IxDbsUg==,type:str]
    qbittorrent-pass: ENC[AES256_GCM,data:pX99HBYlKDUK,iv:xwZXdUXHG1AwdioCBeRCf9mU/yXfVmiF+WvRvm0yVNA=,tag:1/AoZn0jdgnDWiQWMAEthw==,type:str]
    qbittorrent-user: ENC[AES256_GCM,data:yjHkp/Y=,iv:lLp/3PUZJJQF0lWgMmWdlE3+C2AgIuzgruYZSNs1Hlc=,tag:AYdfEgLA9leMaG9tYu2TGA==,type:str]
    radarr-api-key: ENC[AES256_GCM,data:CcvahglbrlVoHtLmLccmwoOlkadWMs7S1LWoRqkIfUI=,iv:9/O2qvRkpSkeoF7J0l9u/P00dNlN9fNI35uB6jDpA64=,tag:iCh32O0kp3xH27QPKyPtGA==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cUpNRzRmd25LVmZBWGlW
            dXVZVnB5RUl1TFJMcnk2bUxNSHZjVm9xTGpBCjMrdVF3RHpEdm82b1BkNEFpWWJV
            OWVrbzVoclNyRzB2Zy9sZW5xRCtMd2cKLS0tIGtuNWNVMEw3RXdNR29CU2F6eVY5
            clZCZFZFZFBZSkxUMVkxQ2pSc1V6TjgKjBdNBfWzQvNZ3kwspErJCdrNH0Bqf9mf
            jWob5PJtStE1T6i6wLtmpDa3/ZeHozw3KD0tkR19FI3bsu+Djg5o0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T11:21:49Z"
    mac: ENC[AES256_GCM,data:Ezzqw3RPQ5DIhLlRmnhUcjTOw8yIc9zymCc1xsTAuff/pJ42GBdWr4M1ZpAYaGkBD9ujsSPk20I28sW3bdikofE0pwfIjrZbWJImmzewt24KLE/oXE+JmcgG8S1HflHHMNZ9o2oWISxXtXRWPmSXiku5xD6sF9TvQ8BTA2hScf8=,iv:sv6j7XjPRQjS0ltoTMx2jttA94fHy/2RzCuLhVcXboI=,tag:I7er6UKNyJKZLUuUUfQmVA==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
