apiVersion: v1
kind: Secret
metadata:
    name: servarr-db-secrets
    namespace: arr
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:lv7mZi8Q,iv:PsJXTiBY2O53pm7FMAn0/3WH7U2dWMgozYCfT/5ejdQ=,tag:22OyA7pxkU+B7XlLjY61Bw==,type:str]
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:da90ycT3,iv:bp6aTq/TFE2pPAYSzbpc/Q00lmhqo8GSFRo4ov8nDL8=,tag:gkrUZshZzjBcPuSXFpiN6A==,type:str]
    PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:KfXGcC9Ycko=,iv:oDZBNQPnDqp5PtPXG553PL2X98gclzKaXLBxBXU0mBk=,tag:ShsUpbIF9ZasRUngwEfogQ==,type:str]
    LIDARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:SkHvws6s,iv:lYoyPyr/EfvVrUPZD9/MRBF8/L9btcoLhBCYzPy4E6w=,tag:XWnTOug1JQdT4HQ7qO1/1w==,type:str]
    LIDARR_CLASSIC__POSTGRES__PASSWORD: ENC[AES256_GCM,data:GLdtiwLUleHfukTX7aQ=,iv:mrgzNI/8uoPRfyFvBgs3f0spsVlKOsiNaG9g0fxPjx8=,tag:hkWVpi3JFSytoqIXPikTJQ==,type:str]
    AUTOBRR__POSTGRES_PASS: ENC[AES256_GCM,data:BlhAZ3KzCg==,iv:7ggTkc4cCjYafCD4RcN322vOjytnem0aSOCLHmP9zVw=,tag:xoPt1CzwWQdz8vfvz9+pyg==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUXJxTHFpVUxIZ1BtcUUr
            Vmt2WHM5Sy9RNzA3b2FQVDZOMWdJZzNYdGh3CkhhZkMwZ2draFFOMjR0NnJaN3l1
            RlFQY0FPazRPeFNjTXE3OXpub1Z0Sm8KLS0tIGtQRkFQYjFsYjZzUWFlVDVTYzBH
            T29QL05YOEdONC9Ga2NXTXd3UWZWSlkKaOJBj6UHo73F3yGjCkwSRZMsqnhdh9Q2
            mqVeJ9CjYLPXHeFrhgWbXbansY2emEi1QRshELtPZlpo17jzf6WicA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-13T20:47:20Z"
    mac: ENC[AES256_GCM,data:Hjub8yZPAeVUFnbbCe9HshKyMc9rjXMows4XVh8wAHchcvOb+BnVXJ9hPCABWrfW8jopun8RdNrdw+RlieHQ5Ri15Y6gBdsMGaXdKEHD5BT066Uuf2Z+6vPK8XMTuazbr6uxhoPGsB+RxGCVeQ6K2XUcVPj0bRpPjkzdTTen/NE=,iv:slc7GYb49IVq4xwVs9qOaScFDjHqDIevttg4mVaAmzw=,tag:prglvf/Lt31EsXw0foM8BQ==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
