apiVersion: v1
kind: Secret
metadata:
    name: servicenow-mid-creds
    namespace: sn
type: Opaque
stringData:
    SN_USER: ENC[AES256_GCM,data:QoNwk+Y=,iv:BQd78HI2fCKIMnwmtsB+NSdNxQOUnPik8wOD4CCkvx0=,tag:pmFVOUac3roRfVgLH6Tvlg==,type:str]
    SN_PASSWD: ENC[AES256_GCM,data:zTKGr0lMOZ7xbFMN,iv:2ahYzHWJnrSP/MABKImPy/cVKZFlePrcIsrQqMDIDaU=,tag:y+u0D5ST609T8EfuW0gPFA==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcWU3c0JWNGIxQ2RJZENF
            am9FSGFMQS85T09kNVlUQXNWV0s1T0ljZkg0Ckkwd2FxQkhYL2ZNVjcwM2Y1a1dW
            K2F2TTBlSkdUVWhDbG80UjBsOHQ2VEEKLS0tIGVaMWI0US8yMnRKbE55d1dTa3Qv
            bU5sUHJzSFhpNUhFUDlCeWZGek5FdzAKjY0zogcg2pM1Ig8PX6Yv3AIGrn0LggaN
            pAa7XvqYDzaLLwL15gQEpKDckSd7uYx3Z/tL+Kh+QQS9FHmoAeIJiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-03T07:59:52Z"
    mac: ENC[AES256_GCM,data:8rtl/R2WAIUfdTQi1F526CNXKum1oc4g+g8eDA1MP3AhhV7pV8xWIPad6jjSBboiG/JDYXzDLBSPS2zENqhbhTetBLKHol96X1ia5clJ2qd6sTJwvj5WF+anqcL0tXFBKESNJY5S96qXiEss0wAIa1lBvA/Jgrb5ptenGzarD6w=,iv:Z19RmJbZK37XLeYGgCjRWZ6kEqeXeE+SuFd8DMoIgXs=,tag:YUCNjZRJxYYZcki7+Ba/gA==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
