apiVersion: v1
kind: Secret
metadata:
    name: extreme-ssh
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Z4ABI+U=,iv:5wFd8+zPfufB7cOAoapO8Ly9VdcXb91vfr74WidrD7Y=,tag:H8hZwj2KJ9y9iLhEFQh58A==,type:str]
    password: ENC[AES256_GCM,data:j3NgdYZpYYc=,iv:CmH/MWwcCpxYLJbTUWgGkxeh6sVXFTEQkuU51Ioevls=,tag:ScvSjPrVh5MsW+AWFVy7ow==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXajlnRWpIb2JWTnZUbTFh
            TTNONDdOQ3VsMjZ4d2VMYndzYnY0ejlFYTEwCnBILzBLK2hxM1VXYmxkbVgvbHN4
            NnI1NDkybWJQdGpwNGxMRDB0Qy9yZm8KLS0tIDA0aDdMM0x4OGw2SUJodjJjT1Qy
            Y243ZmRYYUozd2gxRzh2WnZPLzkvV2cKpYw60Lb0x1kLNiHyq5veiGUuXdvunWen
            I3VQ6vouzYImBg4xlI26hHZR6yviQ78Wbzit7eeJQGdKiJwpnzRsng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T19:12:04Z"
    mac: ENC[AES256_GCM,data:6KavuNU46BYDToRTQpnR5g1sycapZkOYtOhF2mJKIBQlXqRygeaGNktMkIVNyrPGCf60AEiqrhuh/MjiXPqeMT7qwkAvdIhY4rrnuJGDcbAWIwOlbRwe6nUbOdyyT73+6/roGVUT1WGLMbNxD1eE19O1RGR2FV5vSbm2qm+TWV8=,iv:tBLlYiWSMXA1m4A1/ZG8iQjb1LoBF+N44O3AMo/mpvg=,tag:3e2Fy+J3T5atTX3uV9YHTA==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
