apiVersion: v1
kind: Secret
metadata:
    name: truenas-mcp-credentials
    namespace: mcp-system
type: Opaque
stringData:
    TRUENAS_API_KEY: ENC[AES256_GCM,data:N+xWtgELyE0lsj25sTz1/fydGnzPHmvBWEpp+A64+Mpz2euJiIuE1FkGlLbK5i533kKmoJgRmRtCPmgXoW5HB96k,iv:pFH5rLd6dzl7qrGo+1+MOLZADY+Gy0EjQqSI6NeTd/A=,tag:ILkthmWVfNd/thfrBTz1kA==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUUVQSFE4N2J3T0lwbXlM
            RUVYc3NUTURodmpEM25QMVVUZXU5T2c3WVdVCjFYTGJpMmZSbk9QSXQ4RzVSZzlW
            enUvTmhTdUlLK1M4YjV0KzVNNkN4WDgKLS0tIGZHQk1ydmJBNjJOZlNPeHVkY1Zx
            MldKa3ZkZzhQMmlyeFh5aktUQk12eDAKs1oXdKYXACyfrGwTQxstApPhD96tHwsc
            +Hie1tAZYA0Cvln0Y+e2JkOx/vNR6ZtO2RF7I61PkLSfHAz1ihcPYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-04T18:32:23Z"
    mac: ENC[AES256_GCM,data:tsbkzeMxm8LFq6NFc+zih05mvMTlHrmcI1SUivUnWZKdjVlD9kz723tYLsPm7cF3UbaeKUkLMk2OUKA8eroaM2QM5YMUFFQi5nWqgGbftvyM6zYjuAhdHbChwREqfBqlI9RbArmKlImhA37bHxrl/+yrRJYONxS8IM40w391NyY=,iv:1RkcxEuEIUsbvTl+jSu5WHcPJPS4B04InyyxvprRKTg=,tag:gfrzNn33FAm+fsaDDG6fBg==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
