apiVersion: v1
kind: Secret
metadata:
    name: velero-creds
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:mu8OQybOYLm4Dihvl7v5rdu42CLLCv83ygfuIfROGKOkZg92WV0Agj0oiQVdrtkF7/FbLN2swtgszJMMx04XQYqUoMknTB0ibrk6l9nOGdBzx5WCrs2/KZNa5WhsWz6uV/2LiIPWi5RhtpniISXBLV97oNJca5NDlw4NTMgRYTGa/amTbWaMWsTubHKU0kNqEww=,iv:uIshzBbCnMnAyERbleUfOjLwoBxhiEdjOK1gGZgGM8k=,tag:qLKCPCeIBaFXAJ7BfpYUmw==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNy9udVNxS0s5alVZZGJw
            enQ0SVFSeXI2OFJVVVN2eHIwNjM1OWN0Y2xZCmp4S1pONTZNNmVUcXlvdGlEMW54
            L2hkY1B5MHpuZ3Y4S3RtRzUyOXI4eG8KLS0tIFgxRExxS01zL0pqZTczL0x3QjlJ
            TlNsdjJOMmhwMXdSNDMrcGI4aTNJVTAKIJnaQrQv8v4xjnOyHeIW98TrM7zgMNfg
            q6kTuyPF2rvSI3TPfX/htu/FYACEo0sfW6BOE4ZpVHrclMldrtQRzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T17:55:10Z"
    mac: ENC[AES256_GCM,data:CqN6K5+Mgw1eRJc6cVMSqioLw4lAD8u3mFbp4WMYKrR8Uv+gmP9j6nTxSzL0TY7Cb07fWm4eQ+qLmv3YpqqXZv6BGlzGjWu8jo4T6c/3ivrCeoKFTDls7cfL4vN9j07Ib3KfPTIG6ZL+FC2Urxxer6kRpuqO2w3Zl3Tqvhcj0As=,iv:tBQKmZN/DylN76THkjPkRPO0VQBDUeE3TI94enZieSM=,tag:93m8fiYawcLlAGyZI/g/Cw==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
