apiVersion: v1
kind: Secret
metadata:
    name: xray-secrets
    namespace: xray
type: Opaque
stringData:
    private-key: ENC[AES256_GCM,data:8cWyzZe5U6/+a3nEoNj3BGApQhJTXxQ70YUlFXHhGLL+9nGKYpJUkm5ifg==,iv:gr8qee2sJHaCO+rfEj61ATsAmWL83iv3tPNRUbM00Z0=,tag:Zbkl1GqreIO/XskFOO6xXg==,type:str]
    public-key: ENC[AES256_GCM,data:5Iv0Uryzz0NZfK3fyZnxk6pZqe8vG3eZ/tQPhaVEI3mgxXv5lQgPvCJnJw==,iv:0G03dr6IWZjKqe/MNCl02DIpUSUC6IlWjFSnVlXbnRs=,tag:6aQ9lBC3SED7abhQ2NhG0w==,type:str]
    short-id: ENC[AES256_GCM,data:9THxyL49K2g=,iv:fZilpnVeFQaysu9z2kImzDhHOpC22QL3iSiaqocZ0kY=,tag:d/MuOlZT2g8KBvOWn2CvxA==,type:str]
    uuid: ENC[AES256_GCM,data:VwV3iVlzvHjvSDaULYYruk7hNh0syhWi9JeE2rV+vfos8GFr,iv:wp6ZcMyjnW8dYOMhQBRq/RlR9wXhC5gwNbLAIeObF8g=,tag:W49dBiCPKESNZah6pgXqig==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cWxkQmYzL2lDalVqeW9y
            dnhxMEJHdzFTRUtTS3pBbHVLZGI2WXBVUjFnCkNXck5MNm5sUm5yLzdkZ0FjN1pX
            cnFGTmtGSEVzMUFpajN4a0M5Y0doalUKLS0tIFlOVVM3M2RMZm5RNnYwME91VmFw
            SHFLb0F1aEVQbE5BUVNxNTlMVnlWNWcKpCJpGEnQToJu5faem0fn5Zr0huS70qBV
            1xFsJmzM3PUkzmQPrIGB3RVUmWsEv4/ZXp10IHfu/tyYO5LB41Ub2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T11:21:49Z"
    mac: ENC[AES256_GCM,data:EFAUXwNUctH6ux0yHSxpg+Vw8M9ir0UiMZcJZjADdhocH7FnwUANGzSzS/vGbSPWIZEltXaB090O0sDncj6uidj2yk2TJpjO4iWaZ1ACQrFnXlUSsSwdlof/9pJovhfuTs/R8PtecKzTO6abkWPJuJUyiv9pPVPpWjsaslqj9hI=,iv:BQPLIw0HhqPMblFO+nmx5zmpe4LftXk34+mYP1XyguY=,tag:iI2wX7n4TGqFIbG+UE0dAQ==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
