apiVersion: v1
kind: Secret
metadata:
    name: xray-secrets
    namespace: xray
type: Opaque
stringData:
    private-key: ENC[AES256_GCM,data:b2pbYY4+rKkLgXskymHAxGu6Q8sIuO+aJ755jtWrvPbaoG53N95519QTxg==,iv:ElPar/2yPWaSXnFd/yHLx5KFGqyyCJglc2m7qsDLqwU=,tag:ioz11I9BBDe9FICst5/53Q==,type:str]
    public-key: ENC[AES256_GCM,data:399xuTy0LPal3O+OnVqSVmgLQs/WipyeZhm1whCs5KgnCWDQn7qyUrHyJA==,iv:+/WqW8xSbas46Rx/i9web+FnE7JK2QA6c1WTBnMfvR8=,tag:QG+MKSbLYOklVk0aRIKBbQ==,type:str]
    short-id: ENC[AES256_GCM,data:N1Qso2/2v2c=,iv:eHtRIOjNum5GWPPXDq1AHmucvIorcOJEH4YgsQnbec0=,tag:uFpBs3t+ystyy/HlYouTMQ==,type:str]
    uuid: ENC[AES256_GCM,data:TlGEY9RODucxcHhv8BOPIh035v1bD9NdfxiK17JRKug6w++r,iv:nckOS0NHWE6BbJopNV1zCsjQxIAzEaOqsq3/lZ24lYk=,tag:4h5mFfxEsTAiCJVxgyI0kw==,type:str]
sops:
    age:
        - recipient: age1x5pmv4jqhp99mzt089nrm4wn8cd6y4vlt88n8mq0xe30wngasuaqxl4ytl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNTJOWEdlU2oyTGZWT3c2
            eTZhSzlVRTMvZ2RVNUplZmZaNGIwL242bG5BClEwUXlBZWpkUjBLcFVkMzd2RmlT
            cTJLM0c4TUlTS3dDbmV0cTE4N2d3SVEKLS0tIENIeWFFU2J2U2JvQXVpdVViV2Vy
            emxEdEFhZ0hMVG82UEwwL3JVanJlTTAKYB/leq44OnobuuPYBYlVcImxglk0b1GM
            tLOnSJAXCq3NvQv8mMETNJUX7ymc67BYFzl0E/vP22X7oj3TEb1/gA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T10:25:28Z"
    mac: ENC[AES256_GCM,data:UgUN9Vrarp6I1DFkRs5luL5ZuJobaapdvd96eGUdsaj+sxTcWTQqXH+9ZUwe3xPPbFn1XdoMZgaZBcvvEHDdhrhjTblCjCOTgWKpR8HlbvHPfpZyYQzFOmPcptXTLegj31d+DNS+3M4iiRnXRBzG1Dhfy5B5us1mLY8uQ5lF7aw=,iv:v+lf3iFJ7bxuKk60kmagFuH2l0q006O+umGaBng5jxs=,tag:FqbJT3D4PnQc54aho8VJxA==,type:str]
    encrypted_regex: ^(data|stringData|password|secret|token|key|apiKey|client.*)$
    version: 3.12.2
