apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sn-mid-cache
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  volumeMode: Filesystem
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: pv-sn-mid-cache
    volumeAttributes:
      server: 10.10.10.50
      share: /mnt/oliraid/k8s-sn
