apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sn-mid-cache-pvc
  namespace: sn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  volumeName: pv-sn-mid-cache
  resources:
    requests:
      storage: 20Gi
