apiVersion: apps/v1
kind: Deployment
metadata:
  name: sn-mid-server
  namespace: sn
  labels:
    app: mid-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mid-server
  template:
    metadata:
      labels:
        app: mid-server
    spec:
      hostname: k8s-lab-mid-server
      containers:
      - name: mid-server
        image: ghcr.io/pindaroli/custom-mid-server:australia-02-11-2026__patch3-05-25-2026_06-12-2026_1106
        env:
        - name: JAVA_OPTS
          value: "-Dmid.max.extract.file.size=4294967296 -Dmid.download.max_uncompressed_bytes=4294967296 -Dmid.unzip.max_uncompressed_bytes=4294967296 -Dcom.glide.util.ZipUtil.maxSize=4294967296"
        - name: MID_OPTS
          value: "-Dmid.max.extract.file.size=4294967296 -Dmid.download.max_uncompressed_bytes=4294967296 -Dmid.unzip.max_uncompressed_bytes=4294967296 -Dcom.glide.util.ZipUtil.maxSize=4294967296"
        - name: SN_URL
          valueFrom:
            secretKeyRef:
              name: servicenow-mid-creds
              key: SN_URL
        - name: SN_MID_NAME
          value: "MID_Server_K8s"
        envFrom:
        - secretRef:
            name: servicenow-mid-creds
