apiVersion: apps/v1
kind: Deployment
metadata:
  name: sn-mid-server
  namespace: sn
  labels:
    app: mid-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mid-server
  template:
    metadata:
      labels:
        app: mid-server
    spec:
      hostname: k8s-lab-mid-server
      serviceAccountName: sn-discovery-sa
      containers:
      - name: mid-server
        image: ghcr.io/pindaroli/custom-mid-server:australia-02-11-2026__patch3-05-25-2026_06-12-2026_1106
        env:
        - name: MID_INSTANCE_URL
          valueFrom:
            secretKeyRef:
              name: servicenow-mid-creds
              key: SN_URL
        - name: MID_INSTANCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: servicenow-mid-creds
              key: SN_USER
        - name: MID_INSTANCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: servicenow-mid-creds
              key: SN_PASSWD
        - name: MID_SERVER_NAME
          value: "MID_Server_K8s"
        - name: SN_URL
          valueFrom:
            secretKeyRef:
              name: servicenow-mid-creds
              key: SN_URL
        - name: SN_MID_NAME
          value: "MID_Server_K8s"
        - name: JAVA_OPTS
          value: "-Dmid.max.extract.file.size=4294967296 -Dmid.download.max_uncompressed_bytes=4294967296 -Dmid.unzip.max_uncompressed_bytes=4294967296 -Dcom.glide.util.ZipUtil.maxSize=4294967296"
        - name: MID_OPTS
          value: "-Dmid.max.extract.file.size=4294967296 -Dmid.download.max_uncompressed_bytes=4294967296 -Dmid.unzip.max_uncompressed_bytes=4294967296 -Dcom.glide.util.ZipUtil.maxSize=4294967296"
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        volumeMounts:
        - name: mid-storage
          mountPath: /opt/snc_mid_server/agent/work
          subPath: work
        - name: mid-storage
          mountPath: /opt/snc_mid_server/agent/logs
          subPath: logs
        envFrom:
        - secretRef:
            name: servicenow-mid-creds
      volumes:
      - name: mid-storage
        persistentVolumeClaim:
          claimName: sn-mid-cache-pvc
