apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: tdarr-api-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.10.20.61/32
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: tdarr-api-adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - tdarr-api-pool
