apiVersion: v1
kind: Namespace
metadata:
  name: tdarr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdarr-server
  namespace: tdarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tdarr-server
  template:
    metadata:
      labels:
        app: tdarr-server
    spec:
      containers:
        - name: tdarr-server
          image: haveagitgat/tdarr:latest
          ports:
            - containerPort: 8266 # Server API
            - containerPort: 8267 # Web UI
          env:
            - name: TZ
              value: "Europe/Rome"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: serverIP
              value: "0.0.0.0"
            - name: serverPort
              value: "8266"
            - name: webUIPort
              value: "8267"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: tdarr-config
              mountPath: /app/server
            - name: tdarr-db
              mountPath: /app/db
            - name: media
              mountPath: /media
      volumes:
        - name: tdarr-config
          nfs:
            server: 10.10.10.50
            path: /mnt/stripe/k8s-arr/tdarr-config
        - name: tdarr-db
          emptyDir: {}
        - name: media
          nfs:
            server: 10.10.10.50
            path: /mnt/oliraid/arrdata/media
---
apiVersion: v1
kind: Service
metadata:
  name: tdarr-service
  namespace: tdarr
spec:
  selector:
    app: tdarr-server
  ports:
    - name: webui
      port: 8267
      targetPort: 8267
    - name: api
      port: 8266
      targetPort: 8266
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tdarr-ui-internal
  namespace: tdarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tdarr-internal.pindaroli.org`)
      kind: Rule
      middlewares:
        - name: oauth2-auth
          namespace: traefik
      services:
        - name: tdarr-service
          port: 8267
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tdarr-api-internal
  namespace: tdarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tdarr-internal.pindaroli.org`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: tdarr-service
          port: 8266
