apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-media
spec:
  capacity:
    storage: 15000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  volumeMode: Filesystem
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: pv-nfs-media
    volumeAttributes:
      server: 192.168.1.250
      share: /mnt/oliraid/arrdata/media  # 👉 Monta direttamente questa directory!
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-servarr-jellyfin-media
spec:
  capacity:
    storage: 15000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  volumeMode: Filesystem
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: pv-servarr-jellyfin-media
    volumeAttributes:
      server: 192.168.1.250
      share: /mnt/oliraid/arrdata/media  # 👉 Mounts this directory directly!
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: arr
  name: pvc-nfs-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 14000Gi
  volumeName: pv-nfs-media  # 👉 Collega direttamente il PV senza creare sottocartelle
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: arr
  name: servarr-jellyfin-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 14000Gi
  volumeName: pv-servarr-jellyfin-media # 👉 Collega direttamente il PV senza creare sottocartelle
  storageClassName: nfs-csi