jellyfin:
  env:
    TZ: Europe/Rome
  ingress:
    enabled: true
    hosts: ["servarr.local"]
    path: /jellyfin 
  service:
      type: ClusterIP 
      #externalTrafficPolicy: Local
  persistence:
    media:
      existingClaim: servarr-jellyfin-media
    config:
      storageClass: nfs-subdir

sonarr:
  env:
    TZ: Europe/Rome
  persistence:
    storageClass: nfs-subdir

qbittorrent:
  env:
    TZ: Europe/Rome
  persistence:
    storageClass: nfs-subdir

prowlarr:
  env:
    TZ: Europe/Rome
  persistence:
    storageClass: nfs-subdir

jellyseerr:
  env:
    TZ: Europe/Rome
  persistence:
    storageClass: nfs-subdir

bazarr:
  env:
    TZ: Europe/Rome
  persistence:
    storageClass: nfs-subdir

radarr:
  env:
    TZ: Europe/Rome
  persistence:
    storageClass: nfs-subdir

readarr:
  env:
    TZ: Europe/Rome
  persistence:
    storageClass: nfs-subdir


lidarr:
  env:
    TZ: Europe/Rome
  persistence:
    storageClass: nfs-subdir


