apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-servarr-jellyfin-media
spec:
  capacity:
    storage: 15000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  volumeMode: Filesystem
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: pv-servarr-jellyfin-media
    volumeAttributes:
      server: 192.168.1.250
      share: /mnt/oliraid/arrdata/media  # Mounts this directory directly
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: arr
  name: servarr-jellyfin-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 14000Gi
  volumeName: pv-servarr-jellyfin-media # Collega direttamente il PV senza creare sottocartelle
  storageClassName: nfs-csi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-nfs-stripe-arr-conf
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: nfs.csi.k8s.io
parameters:
  # NFS server configuration
  server: 192.168.1.250  # Replace with your actual NFS server
  share: /mnt/stripe/k8s-arr
  
  # Dynamic subdirectory naming: service-name-namespace
  # This creates subdirectories like: /mnt/stripe/k8s/my-service-default
  subDir: ${pvc.metadata.name}
  
  # Set folder permissions to 777 (rwxrwxrwx - full access for all)
  mountPermissions: "0777"
  
  # Volume deletion policy - retain data when PVC is deleted
  onDelete: retain

# Reclaim policy for the persistent volume - delete PV when PVC is deleted
reclaimPolicy: Delete
# Volume binding mode
volumeBindingMode: Immediate
# Allow volume expansion
allowVolumeExpansion: true
# NFS mount options
mountOptions:
  - nfsvers=4.1
  - rsize=1048576
  - wsize=1048576
  - hard
  - timeo=600
  - retrans=2