apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: arr
  name: pv-nfs-media
spec:
  capacity:
    storage: 15000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  volumeMode: Filesystem
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: pv-nfs-media
    volumeAttributes:
      server: 192.168.1.115
      share: /mnt/oliraid/arrdata/media  # 👉 Monta direttamente questa directory!
