apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: arr
  name: servarr-jellyfin-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 14000Gi
  volumeName: pv-servarr-jellyfin-media # 👉 Collega direttamente il PV senza creare sottocartelle
  storageClassName: nfs-csi