apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: arr
  name: pvc-nfs-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 14000Gi
  volumeName: pv-nfs-media  # 👉 Collega direttamente il PV senza creare sottocartelle
