apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servarr-recyclarr-data
  namespace: arr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-nfs-stripe-arr-conf
  resources:
    requests:
      storage: 1Gi
