---
- name: Debug OPNsense API
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    opnsense_url: "https://192.168.2.254"
    api_key: "{{ opnsense_api_key }}"
    api_secret: "{{ opnsense_api_secret }}"
  
  vars_files:
    - "vars/secrets.yml"

  tasks:
    - name: Search Host Overrides
      uri:
        url: "{{ opnsense_url }}/api/unbound/settings/searchHostOverride"
        method: POST
        user: "{{ api_key }}"
        password: "{{ api_secret }}"
        force_basic_auth: yes
        validate_certs: no
        body_format: json
        body:
          current: 1
          rowCount: 100
        return_content: yes
      register: search_result

    - name: Show Results
      debug:
        msg: "{{ search_result.json }}"
