[localhost]
127.0.0.1 ansible_connection=local

[truenas]
10.10.10.50 ansible_user=olindo

[pbs]
10.10.10.100 ansible_user=root

[proxmox]
10.10.10.11 talos_vmid=1300 talos_ip=10.10.20.141 ansible_user=root
10.10.10.21 talos_vmid=2300 talos_ip=10.10.20.142 ansible_user=root
10.10.10.31 talos_vmid=3200 talos_ip=10.10.20.143 ansible_user=root

[switches]
192.168.2.1 ansible_user=admin

[switches:vars]
ansible_network_os=extreme.exos.exos
ansible_connection=ansible.netcommon.network_cli
ansible_network_cli_ssh_type=paramiko
ansible_ssh_private_key_file=~/.ssh/id_rsa_extreme
ansible_ssh_common_args='-o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa'
