#!/bin/zsh
export LC_CTYPE=en_US.UTF-8
echo "🚀 AVVIO MEGA BATCH 100 ARTISTI"
echo "--------------------------------"

folders=(
"/Volumes/arrdata/media/music/Blinblineo.Net __ Lo Mejor Del Genero/"
"/Volumes/arrdata/media/music/Blues Brothers/"
"/Volumes/arrdata/media/music/Bluvertigo/"
"/Volumes/arrdata/media/music/Bob Dylan/"
"/Volumes/arrdata/media/music/Bob Marley & The Wailers/"
"/Volumes/arrdata/media/music/Brand New Heavies/"
"/Volumes/arrdata/media/music/Brecker Brothers/"
"/Volumes/arrdata/media/music/Brian Eno _ Genesis/"
"/Volumes/arrdata/media/music/Britney Spears/"
"/Volumes/arrdata/media/music/Bryan Ferry and Roxy Music/"
"/Volumes/arrdata/media/music/Bud Spencer & Terence Hill/"
"/Volumes/arrdata/media/music/Buster Poindexter/"
"/Volumes/arrdata/media/music/COSMO/"
"/Volumes/arrdata/media/music/CSI/"
"/Volumes/arrdata/media/music/Caetano Veloso/"
"/Volumes/arrdata/media/music/California Guitar Trio/"
"/Volumes/arrdata/media/music/Camerata Bern, Thomas Füri/"
"/Volumes/arrdata/media/music/CapaRezza/"
"/Volumes/arrdata/media/music/Caparezza/"
"/Volumes/arrdata/media/music/Carlo Maria Giulini/"
"/Volumes/arrdata/media/music/Carmen Consoli/"
"/Volumes/arrdata/media/music/Center for Educational Development/"
"/Volumes/arrdata/media/music/Cepero/"
"/Volumes/arrdata/media/music/Charles Aznavour & Edith Piaf/"
"/Volumes/arrdata/media/music/Charlie & the cats/"
"/Volumes/arrdata/media/music/Chato Amaya, Orillo/"
"/Volumes/arrdata/media/music/Cheb Bilal (Algérie)/"
"/Volumes/arrdata/media/music/Checco Zelone/"
"/Volumes/arrdata/media/music/Chopin/"
"/Volumes/arrdata/media/music/Cirilli/"
"/Volumes/arrdata/media/music/Claudio Baglioni/"
"/Volumes/arrdata/media/music/Claudio Bisio/"
"/Volumes/arrdata/media/music/Cochi E Renato/"
"/Volumes/arrdata/media/music/Compay Segundo/"
"/Volumes/arrdata/media/music/Compilations/"
"/Volumes/arrdata/media/music/Corduroy/"
"/Volumes/arrdata/media/music/Cornershop/"
"/Volumes/arrdata/media/music/Cortellesi - Trippy/"
"/Volumes/arrdata/media/music/Credence Clearwater Revival/"
"/Volumes/arrdata/media/music/Césaria Évora/"
"/Volumes/arrdata/media/music/Daddy Yankee/"
"/Volumes/arrdata/media/music/Dan Tyminski/"
"/Volumes/arrdata/media/music/David Bowie/"
"/Volumes/arrdata/media/music/David Sylvian & Ryuichi Sakamo/"
"/Volumes/arrdata/media/music/Dean Martin/"
"/Volumes/arrdata/media/music/Deep Purple/"
"/Volumes/arrdata/media/music/Delta V/"
"/Volumes/arrdata/media/music/Diana Krall/"
"/Volumes/arrdata/media/music/Dimitri Shostakovich/"
"/Volumes/arrdata/media/music/Dinah Shore & Xavier Cugat -/"
"/Volumes/arrdata/media/music/Dj Rosalio/"
"/Volumes/arrdata/media/music/Domenico Modugno/"
"/Volumes/arrdata/media/music/Domingo,  Cecilia Bartoli, Metropolitan/"
"/Volumes/arrdata/media/music/Domingo, Cecilia Bartoli, Metropolitan O/"
"/Volumes/arrdata/media/music/Don Omar/"
"/Volumes/arrdata/media/music/Doobie Brothers/"
"/Volumes/arrdata/media/music/ERIC CLAPTON/"
"/Volumes/arrdata/media/music/Earth Wind And Fire/"
"/Volumes/arrdata/media/music/Elio e Le Storie Tese/"
"/Volumes/arrdata/media/music/Elis Regina e Tom Jobim/"
"/Volumes/arrdata/media/music/Elisa/"
"/Volumes/arrdata/media/music/Elisa & Tiromancino/"
"/Volumes/arrdata/media/music/Elton John/"
"/Volumes/arrdata/media/music/Elvis Presley/"
"/Volumes/arrdata/media/music/Emerson, Lake & Palmer/"
"/Volumes/arrdata/media/music/Emerson, Lake & Powell/"
"/Volumes/arrdata/media/music/Emilia Majello/"
"/Volumes/arrdata/media/music/Eminem & Shaggy -/"
"/Volumes/arrdata/media/music/Emir Kusturica & The No Smoking Orchestr/"
"/Volumes/arrdata/media/music/Enigma/"
"/Volumes/arrdata/media/music/Ennio Morricone/"
"/Volumes/arrdata/media/music/Enrico Ruggeri/"
"/Volumes/arrdata/media/music/Enya/"
"/Volumes/arrdata/media/music/Enzo Ianacci/"
"/Volumes/arrdata/media/music/Enzo Iannacci/"
"/Volumes/arrdata/media/music/Enzo Jannacci/"
"/Volumes/arrdata/media/music/Eric Burdon & The Animals/"
"/Volumes/arrdata/media/music/Eric Clapton/"
"/Volumes/arrdata/media/music/Eric Clepton/"
"/Volumes/arrdata/media/music/Eric Serra/"
"/Volumes/arrdata/media/music/Estrella Morente/"
"/Volumes/arrdata/media/music/Eurythmics/"
"/Volumes/arrdata/media/music/Evelyn Mandac, Stanley Kolk, Etc._ Seiji/"
"/Volumes/arrdata/media/music/F. De Gregori/"
"/Volumes/arrdata/media/music/Fabrizio De Andri/"
"/Volumes/arrdata/media/music/Fabrizio De André/"
"/Volumes/arrdata/media/music/Fatboy Slim/"
"/Volumes/arrdata/media/music/Ferruccio Furlanetto, Paata Burchuladze_/"
"/Volumes/arrdata/media/music/Ferruccio Furlanetto_ Herbert Von Karaja/"
"/Volumes/arrdata/media/music/Filippo Gatti/"
"/Volumes/arrdata/media/music/Fino a qui tutto bene/"
"/Volumes/arrdata/media/music/Fiordaliso/"
"/Volumes/arrdata/media/music/Fiorella Mannoia/"
"/Volumes/arrdata/media/music/Fiorello/"
"/Volumes/arrdata/media/music/Fiorello & Baldini/"
"/Volumes/arrdata/media/music/Fiorello & Baldini - Viva Radio 2/"
"/Volumes/arrdata/media/music/Flaminio e maphia/"
"/Volumes/arrdata/media/music/Francesco De Gregori/"
"/Volumes/arrdata/media/music/Francesco Guccini/"
"/Volumes/arrdata/media/music/Franco Battiato/"
)

count=0
for folder in "${folders[@]}"; do
    count=$((count + 1))
    echo "[$count/100] Elaborazione: $folder"
    beet -c ~/.config/beets/config.yaml import -q "$folder"
done

echo "✅ MEGA BATCH COMPLETATO!"
