apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-main
  namespace: cnpg-system
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-system-trixie
  storage:
    size: 100Gi
    storageClass: local-postgres
  walStorage:
    size: 4Gi
    storageClass: local-postgres
  monitoring:
    enablePodMonitor: false
  backup:
    barmanObjectStore:
      destinationPath: s3://postgres-wal/
      endpointURL: http://10.10.10.50:9000
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: minio-creds
        secretAccessKey:
          key: SECRET_ACCESS_KEY
          name: minio-creds
    retentionPolicy: 30d
  bootstrap:
    initdb:
      database: app
      owner: app
  managed:
    roles:
    - name: n8n
      passwordSecret:
        name: n8n-db-password
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
