apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-prowlarr
  namespace: arr
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: pgloader
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          image: ghcr.io/dimitri/pgloader:latest
          command:
            - pgloader
            - --with
            - "data only"
            - --with
            - "truncate"
            - /config/prowlarr.db
            - postgresql://prowlarr:prowlarr@10.108.78.94:5432/prowlarr
          volumeMounts:
            - name: data
              mountPath: /config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: servarr-prowlarr
