apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector
  namespace: arr
spec:
  containers:
    - name: inspector
      image: alpine:latest
      command: ["sleep", "3600"]
      volumeMounts:
        - name: data
          mountPath: /mnt/data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: servarr-prowlarr
