apiVersion: apps/v1
kind: Deployment
metadata:
  name: kasmweb
  namespace: kasmweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kasmweb
  template:
    metadata:
      labels:
        app: kasmweb
    spec:
      containers:
      - name: kasmweb
        #image: kasmweb/almalinux-9-desktop:1.17.0
        image: olindo/almalinux-9-oli-desktop:latest
        ports:
        - containerPort: 6901
        env:
        - name: VNC_PW
          valueFrom:
            secretKeyRef:
              name: kasmweb-secret
              key: password
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
        volumeMounts:
        - name: shm
          mountPath: /dev/shm
      volumes:
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 512Mi

---

apiVersion: v1
kind: Namespace
metadata:
  name: kasmweb

---

apiVersion: v1
kind: Secret
metadata:
  name: kasmweb-secret
  namespace: kasmweb
type: Opaque
data:
  password: cGFzc3dvcmQ=  # base64 encoded "password"

---

apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: skip-verify
  namespace: kasmweb
spec:
  insecureSkipVerify: true

---

apiVersion: v1
kind: Service
metadata:
  name: kasmweb
  namespace: kasmweb
spec:
  type: ClusterIP
  selector:
    app: kasmweb
  ports:
  - port: 6901
    targetPort: 6901
    protocol: TCP

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kasmweb-ingress-external
  namespace: kasmweb
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kasmweb.pindaroli.org`)
      kind: Rule
      services:
        - name: kasmweb
          port: 6901
      middlewares:
        - name: kasmweb-auth
          namespace: kasmweb
  tls:
    secretName: pindaroli-wildcard-tls

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kasmweb-ingress-internal
  namespace: kasmweb
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kasmweb-internal.pindaroli.org`)
      kind: Rule
      services:
        - name: kasmweb
          port: 6901
  tls:
    secretName: pindaroli-wildcard-tls

---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: kasmweb-auth
  namespace: kasmweb
spec:
  forwardAuth:
    address: http://oauth2-proxy.default.svc.cluster.local/google
    trustForwardHeader: true
    authResponseHeaders:
      - "X-Auth-User"
      - "X-Auth-Email"
